### ISSUE TITLE
[BUG] Ammunition calculating incorrectly

### ISSUE THREAD

**Issue by txm3278** [p4535992/foundryvtt-variant-encumbrance-dnd5e#21]
**Module Version:** v0.31.1

![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/25332081/3091e54f-fc70-49a8-a5ec-159b4c42505b)

**Describe the bug**
Ammunition is not calculating correctly, instead of using the weight 0.075, it is using 1.5. I looked through the settings and could not find anything that could be causing this (using default settings)

**To Reproduce**
Add ammunition with quantity 20 and weight 0.075 to a characters inventory. Observe total weight

**Expected behavior**
Weight should be 20 * 0.075, which is 1.5

**Screenshots**
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/25332081/c4c5c7b6-6eea-4137-a95c-d2edf8f93666)
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/25332081/6d34eb3a-e46c-4358-a34f-df29be8acc9d)

**Browser:**
 - Foundry client

**Foundry Version:** 
11.306
**Game System:** 
DnD5e: 2.2.2

**Comment by p4535992** [comment]
Sorry @txm3278 cannot replicate the issue on my actors can you pass to me the actor json data ?

**Comment by txm3278** [comment]
I ran Find the Culprit and this is only an issue with the item containers module installed. I can't upload a json here, can I dm it to you over discord?

**Comment by p4535992** [comment]
a ok there is a already open issue for that, it's seem something is changed on the item container side and i must find a way to solve it

**Comment by p4535992** [comment]
Should be fixed with 0.13.3 let me know it

**Comment by txm3278** [comment]
Ammunition now calculates correctly, but I am having the same issue described [here.](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/issues/22#issuecomment-1666570744)

**Comment by txm3278** [comment]
Fixed, Thanks!

**Comment by txm3278** [comment]
This bug is back,

![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/25332081/9f0d4c40-23ec-430c-ae58-04593d7bfdde)
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/25332081/52a44a46-2195-4816-8e33-6c9802938ea5)

![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/25332081/4869722a-4f41-4f3e-aa6a-b66f7b866aa8)

Looking through the code, for ammo, it is calculating the weight with itemQuantity * itemWeight. Then it is again multiplying by itemQuantity

**Comment by p4535992** [comment]
I was sure it was  solved...  can you export the actor data json (rename the json with .txt for upload on github)

**Comment by txm3278** [comment]
Tested in the latest update, this is working again! The debug messages do look a bit odd though, mainly the last one,
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/25332081/03178914-8b51-4998-8238-9654caf85969)

**Comment by p4535992** [comment]
i'll fix that
